spring:
  application:
    name: demo-games
  security:
    user:
      name: sunil
      password: sunil
  devtools:
    restart:
      enabled: true
  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    database: h2
  h2:
    console.enabled: true

server:
  port: 7999



